// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrfdzlqneloepidsnwva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyZmR6bHFuZWxvZXBpZHNud3ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTE5NTUsImV4cCI6MjA3MTk2Nzk1NX0.W74LttaxOW0UmUdjbYnIGVedRjuUNHAap1WbBZU32dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});